name: restau_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
 sdk: '>=3.4.1 <4.0.0'

dependencies:
 flutter:
  sdk: flutter
 cupertino_icons: ^1.0.6
 flutter_localizations:
  sdk: flutter
 firebase_core:
 firebase_messaging: 
 permission_handler: ^11.3.1
 firebase_auth: ^5.3.4
 cloud_firestore:
 firebase_storage:
 google_sign_in: ^6.2.2
 flutter_facebook_auth: ^6.0.4
 provider: ^6.0.5
 dio: ^5.3.2
 http: ^1.0.0
 mime: ^1.0.4
 path: ^1.8.3
 get: ^4.6.5
 iconsax: any
 google_fonts: ^6.2.1
 image_picker: ^1.0.7
 file_picker: ^8.1.2
 firebase_analytics: ^11.4.5
 firebase_in_app_messaging: ^0.8.1+5

dev_dependencies:
 flutter_test:
  sdk: flutter
 flutter_lints: any
 flutter_launcher_icons: ^0.13.1

flutter_icons:
 android: true
 ios: true
 image_path: "assets/images/logo.png"
 adaptive_icon_background: "#ffffff"
 adaptive_icon_foreground: "assets/images/logo.png"

flutter:
 uses-material-design: true

 assets:
  - assets/images/
