name: admin_plats_web
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  cached_network_image: ^3.2.1 
  firebase_auth: ^5.3.4
  google_sign_in: ^6.2.2
  flutter_facebook_auth: ^6.0.4
  firebase_core: ^3.9.0
  cloud_firestore:
  firebase_storage:
  provider: ^6.0.5
  dio: ^5.3.2
  http: ^1.2.2
  mime: ^1.0.4
  path: ^1.8.3
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.5
  iconsax: any
  google_fonts: ^6.2.1
  image_picker: ^1.0.7
  file_picker: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: any

flutter:
  uses-material-design: true

  assets:
    - assets/images/
