// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWBjBqidwK3zCkmXuL1WVrUtwcW67X_Bs',
    appId: '1:861244497322:web:efa75fb5cf50984cbc5fd3',
    messagingSenderId: '861244497322',
    projectId: 'appfirebase-7c230',
    authDomain: 'appfirebase-7c230.firebaseapp.com',
    storageBucket: 'appfirebase-7c230.firebasestorage.app',
    measurementId: 'G-EZRPMKWEV0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMElcARiXXRfsrFNtCj82JgDyYCGzoE5c',
    appId: '1:861244497322:android:dd312406eb3b65a7bc5fd3',
    messagingSenderId: '861244497322',
    projectId: 'appfirebase-7c230',
    storageBucket: 'appfirebase-7c230.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLFBMIkDNuXV4iBruscwmHM7Csx_yt6z4',
    appId: '1:861244497322:ios:40d7df4e55e511ccbc5fd3',
    messagingSenderId: '861244497322',
    projectId: 'appfirebase-7c230',
    storageBucket: 'appfirebase-7c230.firebasestorage.app',
    androidClientId: '861244497322-3c40rrnoqiv2ke5lkr9dhqv9b8g4ghk3.apps.googleusercontent.com',
    iosClientId: '861244497322-vji2674hq844uac85g29gnclc4d2kbv5.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminPlatsWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLFBMIkDNuXV4iBruscwmHM7Csx_yt6z4',
    appId: '1:861244497322:ios:40d7df4e55e511ccbc5fd3',
    messagingSenderId: '861244497322',
    projectId: 'appfirebase-7c230',
    storageBucket: 'appfirebase-7c230.firebasestorage.app',
    androidClientId: '861244497322-3c40rrnoqiv2ke5lkr9dhqv9b8g4ghk3.apps.googleusercontent.com',
    iosClientId: '861244497322-vji2674hq844uac85g29gnclc4d2kbv5.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminPlatsWeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWBjBqidwK3zCkmXuL1WVrUtwcW67X_Bs',
    appId: '1:861244497322:web:e9058e276d22d59abc5fd3',
    messagingSenderId: '861244497322',
    projectId: 'appfirebase-7c230',
    authDomain: 'appfirebase-7c230.firebaseapp.com',
    storageBucket: 'appfirebase-7c230.firebasestorage.app',
    measurementId: 'G-Y6Y3VZBFW6',
  );

}